"""
Lightweight UI translation layer for the Streamlit app.

This only translates the app's own interface "chrome" (nav, labels, buttons,
page titles/subtitles, common metric names) -- it does not translate values
that come from the user's own data (product names, store names, column
names) or free-text sentences generated by the recommendation/insights
engine, since those are derived from the store owner's real data and
mistranslating them could misrepresent it. Numbers, dates and currency
formatting are also left as-is.

Usage:
    from api.i18n import t, LANGUAGES
    t("nav_dashboard")               # -> "Dashboard" or "لوحة التحكم"
"""

LANGUAGES = {"en": "English", "ar": "العربية"}

_STRINGS = {
    # ---- Auth screen ----
    "app_eyebrow": {"en": "RETAIL AI", "ar": "الذكاء الاصطناعي للتجزئة"},
    "app_title": {"en": "Pricing intelligence, made simple.",
                  "ar": "ذكاء التسعير، بأسلوب مبسّط."},
    "app_subtitle": {"en": "Upload your sales history, train on your own data, and turn forecasts into clear business decisions.",
                      "ar": "ارفع سجل مبيعاتك، دَرِّب النموذج على بياناتك، وحوّل التوقعات إلى قرارات عمل واضحة."},
    "tab_sign_in": {"en": "Sign in", "ar": "تسجيل الدخول"},
    "tab_create_account": {"en": "Create account", "ar": "إنشاء حساب"},
    "field_username": {"en": "Username", "ar": "اسم المستخدم"},
    "field_password": {"en": "Password", "ar": "كلمة المرور"},
    "field_business_name": {"en": "Business / store name", "ar": "اسم النشاط التجاري / المتجر"},
    "btn_sign_in": {"en": "Sign in", "ar": "تسجيل الدخول"},
    "btn_create_account": {"en": "Create account", "ar": "إنشاء الحساب"},
    "err_incorrect_login": {"en": "Incorrect username or password.", "ar": "اسم المستخدم أو كلمة المرور غير صحيحة."},
    "msg_account_created_suffix": {"en": " You can now sign in.", "ar": " يمكنك الآن تسجيل الدخول."},
    "language_label": {"en": "Language", "ar": "اللغة"},

    # ---- Navigation ----
    "nav_dashboard": {"en": "Dashboard", "ar": "لوحة التحكم"},
    "nav_forecast": {"en": "Forecast", "ar": "التوقعات"},
    "nav_pricing": {"en": "Price Simulator", "ar": "محاكي الأسعار"},
    "nav_compare": {"en": "Compare Actions", "ar": "مقارنة الإجراءات"},
    "nav_recommend": {"en": "Recommendations", "ar": "التوصيات"},
    "nav_insights": {"en": "Business Insights", "ar": "رؤى الأعمال"},
    "nav_assistant": {"en": "AI Assistant", "ar": "المساعد الذكي"},
    "nav_menu_label": {"en": "WORKSPACE", "ar": "قائمة العمل"},
    "logout": {"en": "Log out", "ar": "تسجيل الخروج"},
    "model_management_expander": {"en": "Model management", "ar": "إدارة النموذج"},
    "upload_retrain_btn": {"en": "Upload / retrain model", "ar": "رفع / إعادة تدريب النموذج"},

    # ---- Sidebar: scenario ----
    "scenario_header": {"en": "Scenario", "ar": "السيناريو"},
    "scenario_caption": {"en": "Your dashboard is already ready. Change these settings only when you want a different analysis.",
                          "ar": "لوحتك جاهزة بالفعل. غيّر هذه الإعدادات فقط عندما تريد تحليلاً مختلفاً."},
    "store_label": {"en": "Store / location", "ar": "المتجر / الموقع"},
    "single_location": {"en": "Single-location account", "ar": "حساب بموقع واحد"},
    "forecast_date_label": {"en": "Forecast date", "ar": "تاريخ التوقع"},
    "objective_label": {"en": "Business objective", "ar": "هدف العمل"},
    "objective_balanced_profit": {"en": "Balanced (revenue + profit)", "ar": "متوازن (الإيراد + الربح)"},
    "objective_balanced": {"en": "Balanced", "ar": "متوازن"},
    "objective_revenue": {"en": "Maximize Revenue", "ar": "زيادة الإيراد"},
    "objective_profit": {"en": "Maximize Profit", "ar": "زيادة الربح"},
    "objective_demand": {"en": "Maximize Demand", "ar": "زيادة الطلب"},
    "product_label": {"en": "Product", "ar": "المنتج"},
    "promo_checkbox": {"en": "Promotion running on this date?", "ar": "هل يوجد عرض ترويجي في هذا التاريخ؟"},
    "holiday_checkbox": {"en": "Holiday on this date?", "ar": "هل هذا التاريخ عطلة؟"},
    "current_price_cost_caption": {
        "en": "Current price: {price:.2f} EGP · Current cost: {cost:.2f} EGP -- pulled from this product's own historical data, not a guess.",
        "ar": "السعر الحالي: {price:.2f} ج.م · التكلفة الحالية: {cost:.2f} ج.م -- مأخوذة من بيانات هذا المنتج الفعلية، وليست تخميناً.",
    },
    "pricing_assumptions_expander": {"en": "Pricing assumptions", "ar": "افتراضات التسعير"},
    "base_price_label": {"en": "Base price ($)", "ar": "السعر الأساسي ($)"},
    "elasticity_label": {"en": "Price elasticity", "ar": "مرونة السعر"},
    "elasticity_help": {"en": "More negative means demand is more price-sensitive. This is a disclosed assumption, not measured from your data.",
                         "ar": "كلما كانت القيمة أكثر سلبية، زادت حساسية الطلب للسعر. هذا افتراض مُعلَن وليس مقاساً من بياناتك."},
    "include_profit_checkbox": {"en": "Include profit calculations", "ar": "تضمين حسابات الربح"},
    "unit_cost_label": {"en": "Unit cost ($)", "ar": "تكلفة الوحدة ($)"},
    "scenario_changed_warning": {"en": "Scenario changed — click **Update analysis** to refresh the results.",
                                  "ar": "تم تغيير السيناريو — اضغط **تحديث التحليل** لتحديث النتائج."},
    "scenario_matches_caption": {"en": "Your results match the current scenario.", "ar": "نتائجك مطابقة للسيناريو الحالي."},
    "update_analysis_btn": {"en": "Update analysis", "ar": "تحديث التحليل"},
    "last_updated_caption": {"en": "Last updated at {time}", "ar": "آخر تحديث في {time}"},

    # ---- Page headers: (eyebrow, title, subtitle) ----
    "hdr_dashboard_eyebrow": {"en": "RETAIL INTELLIGENCE", "ar": "ذكاء التجزئة"},
    "hdr_forecast_eyebrow": {"en": "FORECAST", "ar": "التوقع"},
    "hdr_forecast_title": {"en": "Demand forecast", "ar": "توقع الطلب"},
    "hdr_forecast_subtitle": {"en": "See expected {target}, trend direction, and the evidence behind the prediction.",
                               "ar": "اطّلع على {target} المتوقع، واتجاه الأداء، والأدلة وراء التوقع."},
    "hdr_pricing_eyebrow": {"en": "PRICING", "ar": "التسعير"},
    "hdr_pricing_title": {"en": "Price simulator", "ar": "محاكي الأسعار"},
    "hdr_pricing_subtitle": {"en": "Explore how different prices may affect demand, revenue, and profit.",
                              "ar": "استكشف كيف يمكن أن تؤثر الأسعار المختلفة على الطلب والإيراد والربح."},
    "hdr_compare_eyebrow": {"en": "SCENARIOS", "ar": "السيناريوهات"},
    "hdr_compare_title": {"en": "Compare actions", "ar": "مقارنة الإجراءات"},
    "hdr_compare_subtitle": {"en": "See the revenue impact of the available business actions side by side.",
                              "ar": "قارن أثر كل إجراء متاح على الإيراد جنباً إلى جنب."},
    "hdr_recommend_eyebrow": {"en": "DECISION", "ar": "القرار"},
    "hdr_recommend_title": {"en": "Recommended action", "ar": "الإجراء الموصى به"},
    "hdr_recommend_subtitle": {"en": "A clear decision backed by the forecast and the selected business objective.",
                                "ar": "قرار واضح مبني على التوقع وهدف العمل المختار."},
    "hdr_insights_eyebrow": {"en": "INSIGHTS", "ar": "الرؤى"},
    "hdr_insights_title": {"en": "Business insights", "ar": "رؤى الأعمال"},
    "hdr_insights_subtitle": {"en": "Understand patterns in your own sales history and where performance changes.",
                               "ar": "افهم الأنماط في سجل مبيعاتك ومتى يتغيّر الأداء."},

    # ---- Common labels used across pages ----
    "run_first_info": {"en": "Run an analysis first.", "ar": "قم بإجراء تحليل أولاً."},
    "set_scenario_info": {"en": "Set your scenario in the sidebar and run an analysis first.",
                           "ar": "حدّد سيناريوك من الشريط الجانبي وقم بإجراء تحليل أولاً."},
    "run_to_forecast_info": {"en": "Run an analysis to generate a forecast.", "ar": "قم بإجراء تحليل لإنشاء توقع."},
    "why_forecast_header": {"en": "Why this forecast?", "ar": "لماذا هذا التوقع؟"},
    "forecast_source_caption": {"en": "Forecast source: real prediction from your trained model.",
                                 "ar": "مصدر التوقع: تنبؤ حقيقي من النموذج المُدرَّب على بياناتك."},
    "recommended_move_header": {"en": "Recommended move", "ar": "الإجراء الموصى به"},
    "expected_impact_header": {"en": "Expected impact", "ar": "الأثر المتوقع"},
    "expected_impact_caption": {"en": "Based on the selected scenario", "ar": "بناءً على السيناريو المختار"},

    # ---- Upload / retrain page ----
    "hdr_upload_eyebrow": {"en": "MODEL SETUP", "ar": "إعداد النموذج"},
    "hdr_upload_title": {"en": "Connect your store data", "ar": "اربط بيانات متجرك"},
    "hdr_upload_subtitle": {"en": "Train the model on your own sales history. Nothing is simulated during training.",
                             "ar": "درّب النموذج على سجل مبيعاتك الفعلي. لا يوجد أي محاكاة أثناء التدريب."},
    "upload_section_title": {"en": "Upload sales history", "ar": "رفع سجل المبيعات"},
    "upload_section_caption": {"en": "CSV format. A date column and sales/revenue column are required.",
                                "ar": "بصيغة CSV. يجب توفر عمود تاريخ وعمود مبيعات/إيراد."},

    # ---- Dashboard ----
    "dashboard_greeting": {"en": "Good to see you, {store_name}", "ar": "أهلاً بك، {store_name}"},
    "dashboard_subtitle": {"en": "A decision-focused view of your store performance, forecast, and model health.",
                            "ar": "نظرة مركّزة على أداء متجرك وتوقعاتك وحالة النموذج."},
    "model_ready_status": {"en": "MODEL READY", "ar": "النموذج جاهز"},

    # ---- Assistant ----
    "hdr_assistant_eyebrow": {"en": "ASSISTANT", "ar": "المساعد"},
    "hdr_assistant_title": {"en": "AI assistant", "ar": "المساعد الذكي"},
    "hdr_assistant_subtitle": {"en": "Ask questions about forecasts, pricing, recommendations, and your business insights.",
                                "ar": "اطرح أسئلة عن التوقعات والتسعير والتوصيات ورؤى عملك."},
    "assistant_intro_title": {"en": "Your retail decision copilot", "ar": "مساعدك في قرارات التجزئة"},
    "assistant_intro_copy": {"en": "Ask a business question in plain English. The assistant uses the loaded model and your store data to answer it.",
                              "ar": "اطرح سؤال عمل بلغة بسيطة. يستخدم المساعد النموذج المُحمَّل وبيانات متجرك للإجابة."},
}


def get_lang():
    """Read the current language from Streamlit session state (default English)."""
    try:
        import streamlit as st
        return st.session_state.get("lang", "en")
    except Exception:
        return "en"


def t(key, **kwargs):
    """Look up `key` in the active language, falling back to English, then
    to the key itself so a missing translation never crashes the page."""
    lang = get_lang()
    entry = _STRINGS.get(key)
    if entry is None:
        return key
    text = entry.get(lang, entry.get("en", key))
    if kwargs:
        try:
            return text.format(**kwargs)
        except Exception:
            return text
    return text


def is_rtl():
    return get_lang() == "ar"


RTL_CSS = """
<style>
[data-testid="stAppViewContainer"], [data-testid="stSidebar"] {
    direction: rtl;
}
[data-testid="stAppViewContainer"] *, [data-testid="stSidebar"] * {
    text-align: right;
}
[data-testid="stMetricValue"], [data-testid="stMetricLabel"], [data-testid="stMetricDelta"] {
    text-align: right;
}
.stDataFrame, .stDataFrame * {
    direction: ltr;
}
input, textarea {
    text-align: right;
}
</style>
"""

# Known backend messages (from api/accounts.py) that we translate at the UI
# layer rather than touching the backend, since they are plain, fixed
# strings and this keeps the change localized to the presentation layer.
_BACKEND_MESSAGES = {
    "Username must be 3-32 characters: letters, numbers, - or _ only.":
        "يجب أن يتكون اسم المستخدم من 3-32 حرفاً: أحرف، أرقام، - أو _ فقط.",
    "Password must be at least 6 characters.":
        "يجب أن تتكون كلمة المرور من 6 أحرف على الأقل.",
    "That username is already taken.":
        "اسم المستخدم هذا مُستخدم بالفعل.",
    "Account created.":
        "تم إنشاء الحساب.",
}


def translate_backend_message(message: str) -> str:
    if get_lang() != "ar":
        return message
    return _BACKEND_MESSAGES.get(message, message)
